---
app_dir: /opt/unhan/sikerjasama/frontend
app_name: unhan-sikerjasama-frontend
app_server_name: kerma.d.pusilkom.com
app_source: "{{ project_dir|quote }}"

proxy_env:
  http_proxy: proxy.cs.ui.ac.id:8080
  https_proxy: proxy.cs.ui.ac.id:8080
